export const GET_LIST_NEWS = "GET_LIST_NEWS";
export const GET_LIST_HEADING = "GET_LIST_HEADING";
export const GET_LIST_SELECTION = "GET_LIST_SELECTION";

export const ACT_REGISTER_USER = "ACT_REGISTER_USER";
export const ACT_LOGOUT_USER = "ACT_LOGOUT_USER";
